### ISSUE TITLE
Future?

### ISSUE THREAD

**Issue by adamramadhan** [stackdot/NodeJS-Git-Server#2]
hello, i see this is a very good project, can i know the future enchantment? maybe i could help. i mean like http based API to add users and list etc.

**Comment by TobiasNickel** [comment]
you see, i currently get active about git server. I would like to support this project. 

my thoughts:
I like it is very simple to setup. (if we update used dependencies to newer versions)
I would like to see, that it is possible to run the api handler as middleware in express and koa. 
I see, it is already possible to add and remove users to the repos user array at runtime.
supporting middlewares, it would also be possible to change repos ar runtime.
It would be nice if the eventhooks can get changed at runtime. 

In this way, gitserver would become a great module to get integrated into other projects and still provide simple solution to host repos out of the box.

**Comment by qrpike** [comment]
@TobiasNickel I agree, since it uses http git protocol instead of the ssh protocol, using an express/restify style setup would make sense and allow cool things to be done with it. I think that approach would solve a lot of the things you're looking to solve.
