### ISSUE TITLE
hello i'd like to contribute.;-)

### ISSUE THREAD

**Issue by bbsalsero** [stackdot/NodeJS-Git-Server#23]
this is an awsome project, would it be nicer with a web gui like github?

i would work on it if community like to and , if some of you want to participate it 'll be awsome!!!

**Comment by qrpike** [comment]
Absolutely, that would be perfect. I've been wanting to add a UI for a while now. Just make sure its separated from the API for people who don't want to use it.

What technologies are you thinking about using for the UI?

**Comment by bhgraham** [comment]
Absolutely, I have had a need for something to replace github/gitlab that
is lighter weight than gitlab. Node.js would be perfect.


Benjamin H. Graham
http://bman.io

**Comment by bbsalsero** [comment]
Great!!!!!
I will create a full js project
Based on some of my works



Envoyé à partir de mon Windows Phone
________________________________
De : Quinton Pike<mailto:notifications@github.com>
Envoyé : ‎01/‎04/‎2015 17:00
À : stackdot/NodeJS-Git-Server<mailto:NodeJS-Git-Server@noreply.github.com>
Cc : bbsalsero<mailto:iatus@live.fr>
Objet : Re: [NodeJS-Git-Server] hello i'd like to contribute.;-) (#23)

Absolutely, that would be perfect. I've been wanting to add a UI for a while now. Just make sure its separated from the API for people who don't want to use it.

What technologies are you thinking about using for the UI?

---

**Comment by bbsalsero** [comment]
We are on the same vibe😃, js powaaaa!!!!!!

________________________________
De : Benjamin H. Graham<mailto:notifications@github.com>
Envoyé : ‎01/‎04/‎2015 17:11
À : stackdot/NodeJS-Git-Server<mailto:NodeJS-Git-Server@noreply.github.com>
Cc : bbsalsero<mailto:iatus@live.fr>
Objet : Re: [NodeJS-Git-Server] hello i'd like to contribute.;-) (#23)

Absolutely, I have had a need for something to replace github/gitlab that
is lighter weight than gitlab. Node.js would be perfect.


Benjamin H. Graham
http://bman.io

On Wed, Apr 1, 2015 at 10:00 AM, Quinton Pike <notifications@github.com>
wrote:

> Absolutely, that would be perfect. I've been wanting to add a UI for a
> while now. Just make sure its separated from the API for people who don't
> want to use it.
>
> What technologies are you thinking about using for the UI?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stackdot/NodeJS-Git-Server/issues/23#issuecomment-88515094>
> .
>


---

**Comment by bbsalsero** [comment]
We should talk about it,
Discuss about what we want to inside

Envoyé à partir de mon Windows Phone
________________________________
De : Benjamin H. Graham<mailto:notifications@github.com>
Envoyé : ‎01/‎04/‎2015 17:11
À : stackdot/NodeJS-Git-Server<mailto:NodeJS-Git-Server@noreply.github.com>
Cc : bbsalsero<mailto:iatus@live.fr>
Objet : Re: [NodeJS-Git-Server] hello i'd like to contribute.;-) (#23)

Absolutely, I have had a need for something to replace github/gitlab that
is lighter weight than gitlab. Node.js would be perfect.


Benjamin H. Graham
http://bman.io

On Wed, Apr 1, 2015 at 10:00 AM, Quinton Pike <notifications@github.com>
wrote:

> Absolutely, that would be perfect. I've been wanting to add a UI for a
> while now. Just make sure its separated from the API for people who don't
> want to use it.
>
> What technologies are you thinking about using for the UI?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stackdot/NodeJS-Git-Server/issues/23#issuecomment-88515094>
> .
>


---

**Comment by qrpike** [comment]
I prefer backbone.js or maybe angular.

**Comment by bhgraham** [comment]
backbone++

I just see a larger learning curve to get other contributors for angular,
and I don't see it as the long term solution anyway.  As long as everything
is API driven, others can make clients and whatever UI using their choice
of framework.


Benjamin H. Graham
http://bman.io

**Comment by bbsalsero** [comment]
There is no way i ll use ng, i use it daily at m'y work and i can tell, for me it is a pièce of crap. This Is not made for contributive work.

Because of this, i develop a new mit Framework , i can show you, you Will give me some good news.

**Comment by bbsalsero** [comment]
about portabilty, i think than using connector for some langage could be a nice idea, this way the interface can be embeded in any project.

**Comment by qrpike** [comment]
True, I like that

*Quinton Pike*
Previously at: *Turner, **CNN, Google* and now at:* TST*
http://qpike.com - and If you must: 404-402-7441

**Comment by bbsalsero** [comment]
so first i'm gonna create a new project at github ( for now ;-) )

so i need a name for the project what would you think about "GITFACE"

**Comment by qrpike** [comment]
That works for me.

*Quinton Pike*
Previously at: *Turner, **CNN, Google* and now at:* TST*
http://qpike.com - and If you must: 404-402-7441

**Comment by bbsalsero** [comment]
so be it

**Comment by bbsalsero** [comment]
https://github.com/bbsalsero/GITFACE

**Comment by qrpike** [comment]
Nice!

*Quinton Pike*
Previously at: *Turner, **CNN, Google* and now at:* TST*
http://qpike.com - and If you must: 404-402-7441

**Comment by bbsalsero** [comment]
there is an issue open for  every one who'd like to contribute to this new project.

so go there and let's start talking about it.
