### ISSUE TITLE
issues with async 2.0

### ISSUE THREAD

**Issue by gabrielcsapo** [stackdot/NodeJS-Git-Server#36]
`filter, reject, some, every, and related functions now expect an error as the first callback argument, rather than just a simple boolean. Pass null as the first argument, or use fs.access instead of fs.exists. (#118, #774, #1028, #1041)`

causes 

```
/root/node-distribute/node_modules/git-server/host.js:269
          if (results.length > 0) {
                     ^
TypeError: Cannot read property 'length' of null
```

**Comment by jetiny** [comment]
me too.
