### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by CodeartistSerge** [stackdot/NodeJS-Git-Server#44]
Installed git-server from this repo, running on node v8.1.2

Got this error, when trying to use the example code, but run into the error below

![The Error](https://user-images.githubusercontent.com/17958648/30243432-701d3040-95ec-11e7-8762-0c8d28877809.jpg)

**Comment by FL0RIANMEYER** [comment]
Delete socket.io of node_modules/dnode/socket.io
Install latest socket.io to node_modules/socket.io

or update node_modules/socket.io to latest

Solved same issue

**Comment by CodeartistSerge** [comment]
Works like a charm, thanx
