### ISSUE TITLE
Hosting bare git repos on a separate server?

### ISSUE THREAD

**Issue by saoudrizwan** [stackdot/NodeJS-Git-Server#47]
Hello, thank you so much for the amazing repo.

I understand that in your implementation, you use `git-upload-pack` and `git-receive-pack` processes to allow the client and server to talk to each other (figure out what packets the other needs, etc.) 
To my knowledge, this git command accepts a local directory, but what if I host all my bare git repositories on a separate server, like an AWS S3 bucket? Could I stream a remote bare repo to these git commands, that then stream the necessary packets to the client? 
I don't want to host all my bare git repos on my heroku instance, since the storage is ephemeral and limited. Any guidance would be appreciated!

**Comment by ghost** [comment]
I think you need to check out the snapshots functionality on AWS. S3 is for assets that don’t change such as images, videos etc - stuff you might want to download usually. This isn’t really the right forum for this kind of question though as it’s more about cloud architecture than a node library.
