### ISSUE TITLE
Custom authentication handling

### ISSUE THREAD

**Issue by zefir-git** [stackdot/NodeJS-Git-Server#49]
Is it possible to handle authentication manually using this library?

I need to be able to authenticate users with a password hash or key.

**Comment by TobiasNickel** [comment]
not as a callback or so, but as shown in the readme, you can when defining the repo add a list of users with r and w permission. 

So once there is a push or pull, from a git client, these credentials are tested. 

once the user does try use the git server you can not live query a user table or system. But You can at the runtime of the server keep the userlist up to date. maybe as pubsub, pulling or provide a custom api  for example with express.js so the user managing system can post userupdates into the git-server.

so, options are there, however they are not very convenient or incredible scalable.

**Comment by zefir-git** [comment]
Thank you for the information.
